<?php
$title = 'Delete Email';
$this->headTitle($title);
?>
<!--<h1><?php echo $this->escapeHtml($title); ?></h1>-->

<p style="margin:25px 0;">Are you sure that you want to delete
    '<?php echo $this->escapeHtml($emailapp->name); ?>'?
</p>
<?php
$url = $this->url('emailapp', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $emailapp->id; ?>" />
    <input type="submit" name="del" class="btn btn-default" value="Yes" style="margin-left:0;" />
    <input type="submit" name="del" class="btn btn-default" value="No" style="margin-left:0;" />
</div>
</form>

