<?php
$title = 'Edit Email List';
$this->headTitle($title);
//echo '<pre>'; print_r($form); echo '</pre>';
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('emailapp',array('action' => 'edit','id'  => $this->id,)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')); ?>
<table class="table-form">
    <tr>                 
        <td class="title"><?php echo $this->formLabel($form->get('name')); ?></td>
        <td><?php echo $this->formText($form->get('name')); ?></td>
    </tr>
    <tr>                 
        <td class="title"><?php echo $this->formLabel($form->get('email')); ?></td>
        <td><?php echo $this->formText($form->get('email')); ?></td>
    </tr> 
    <tr>                 
        <td class="title"><?php echo $this->formLabel($form->get('content')); ?></td>
        <td><?php echo $this->formTextarea($form->get('content')); ?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')); ?>&nbsp;&nbsp;
            <a href="<?php echo $this->url('emailapp');?>" class="btn btn-large btn-primary">Cancel</a>
        </td>
    </tr>
</table>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">    
    make_wyzz('textarea-editor');
</script>