 <?php
 $title = 'Email List';
 $this->headTitle($title);
 ?>
<script type="text/javascript">
 $('document').ready(function()
 {
         $('.messageCheckbox').click(function(e) 
         { 
                var messageCheckboxes = [];
                $("input:checkbox[name=selectedmail]:checked").each(function()
                {
                     messageCheckboxes.push($(this).val());
                });
                document.getElementById('maillist').value = messageCheckboxes;                             //alert(messageCheckboxes);
        });
        $('#sendid').click(function() {
            

        if ($('#maillist').val() == '') 
            {
                alert('Please select atleast one email address');
                return false;

            }
            else
            {
                $('#sendform').submit();
            }
        });
 });

 </script>

<div class="row">
    <div class="col-md-12">
        <h3><?php echo $this->escapeHtml($title); ?></h3>
        <?php
if($this->flashMessenger()->render('error')!='') 
{
    echo '<div class="alert alert-error">'.$this->flashMessenger()->render('error').'</div>';
}
if($this->flashMessenger()->render('success')!='') 
{
    echo '<div class="alert alert-success">'.$this->flashMessenger()->render('success').'</div>';
}
if($this->flashMessenger()->render('info')!='') 
{
    echo '<div class="alert alert-info">'.$this->flashMessenger()->render('info').'</div>';
}
?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <form name ="sendform" id="sendform" action="<?php echo $this->url('emailapp', array('action'=>'sendmail'));?>" method="POST">
                <?php echo $this->translate('Results: ') ?><?php echo $this->escapeHtml(count($emailapp));?>
                <span style="float:right;font-size:12px;">
                    <a href="<?php echo $this->url('emailapp', array('action'=>'import'));?>">Import</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $this->url('emailapp', array('action'=>'importtemp'));?>">Sendmail with Template</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a style="font-size: 13px;" id="sendid" href="#">Send Mail</a>
                    <input type="hidden" name="maillist" id="maillist"/> 
                    <!--
                    &nbsp;&nbsp;
                    <a href="<?php echo $this->url('emailapp', array('action'=>'add'));?>">Add New</a></span> --> 
                </form> 
            </div>
            <table class="table <?php if(count($emailapp)>0): echo 'pagination-table'; endif;?>">
              <thead>
                 <tr class="panel panel-default">
                        <th class="panel-heading" id="data-sorter-false"> </th>
                         <th class="panel-heading">Name</th>
                         <th class="panel-heading">Email ID</th>
                         <th class="panel-heading">Imported Date</th>
                         <th class="panel-heading">Mail Sent</th>
                         <th class="panel-heading align-center" id="data-sorter-false">Action</th>
                 </tr>
                 </thead>
                 <tbody>	
                 <?php
                 if(count($emailapp)>0) { foreach ($emailapp as $emailapps) : ?>
                    <tr class="panel panel-default">
                        <td><input type="checkbox" class="messageCheckbox" name="selectedmail" value="<?php echo $emailapps->id ;?>"> </td>
                        <td><?php echo $emailapps->name;?></td> 
                        <td><?php echo $emailapps->email;?></td> 
                        <td><?php 
                        if($emailapps->import_date != '0000-00-00 00:00:00') 
                        { echo $this->escapeHtml(ucwords($emailapps->import_date)); };?></td>
                        <td><?php 
                        if($emailapps->mail_sent != '0000-00-00 00:00:00') 
                        { echo $this->escapeHtml(ucwords($emailapps->mail_sent)); };?></td> 
                        <td id="data-sorter-false">
                            
                            <a href="<?php echo $this->url('emailapp',array('action'=>'view', 'id' => $emailapps->id));?>" title="View"><img src="<?php echo $this->basePath().'/img/icon_view.png'?>"></a>&nbsp;
                            <a href="<?php echo $this->url('emailapp',array('action'=>'edit', 'id' => $emailapps->id));?>" title="Edit"><img src="<?php echo $this->basePath().'/img/icon_edit.png'?>"></a>&nbsp;
                            <a href="<?php echo $this->url('emailapp',array('action'=>'delete', 'id' => $emailapps->id));?>" title="Delete"><img src="<?php echo $this->basePath().'/img/icon_delete.png'?>"></a>
                        </td>
                    </tr>
                 <?php endforeach; } else { ?>
                 <tr class="panel panel-default">
                        <td colspan="7" class="align-center"><?php echo $this->escapeHtml('No Records..');?></td>    
                 </tr>
                 <?php } ?>
                 </tbody>
             </table>	
        </div>
    </div> 
 </div>
