<?php
$title = 'Send Email List';
$this->headTitle($title);
?><h3><?php echo $this->escapeHtml($title); ?></h3><br><br>
<script>
    $(document).ready(function(){ 
                     
        $("#showcase").hide();
        $("input[name='import_date'], input[name='import_date']").datepicker({
             dateFormat: 'yy-mm-dd',
             changeMonth: true,
             changeYear: true             
        });
    }); 
    function checkFile(fieldObj)
    {
        var FileName  = fieldObj.value;
        var FileExt = FileName.substr(FileName.lastIndexOf('.')+1);
        /*if(FileExt != 'csv')
        {
            alert('Please upload only CSV file.');
        }   */ 
        return true;
    }
    function getTempDetails(tempid)
    {
        $.ajax({
            url: "<?php echo $this->url('emailapp',array('action'=>'tempdetails'))?>",
            type: 'POST',
            data: ({ tempid: tempid }),            
            success: function(response) {                
                    //var result = $('<div />').append(response).find('#showresults').html();
                    //$('#showresults').html(result); 
                    //console.log(response);
                    var data = JSON.parse(response);                                    
                     $('input[name="from_name"]').val(data.from_name);
                     $('input[name="from_email"]').val(data.from_email);
                     $('input[name="subject"]').val(data.subject);                    
                     $('#wysiwygtextarea-editor').contents().find('body').html(data.body);
                    // alert(response);
                    //console.log(data.body)
                    // $.each(response, function(index, element) {
                    //  $('body').append($('<div>', {
                    //     text: element.name
                    //     }));
                    //  });                                                                    
             }
       });        
    }
</script>

<script type="text/javascript">
        
        $(document).ready(function(){
            if($("#template").val()=="empty"){                   
                    $(".showcase").addClass("hidden");
                }
        $("#template").change(function(){
                if($(this).val()=="empty"){                   
                    $(".showcase").addClass("hidden");
                }
                else
                {
                     $(".showcase").removeClass("hidden")
                }
                
            });
       });
</script>

    <style type="text/css">
        .hidden{
            display: none;

         }
    </style>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('emailapp', array('action' => 'sendmailOld')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<table class="table-form">
    <tr>                 
        <td class="title"><?php echo $this->formLabel($form->get('template_name')); ?></td>
        <td><?php echo $this->formSelect($form->get('template_name')); ?></td>
    </tr>
    <tr>                 
        <td class="title"><?php echo $this->formLabel($form->get('import_date')); ?></td>
        <td><?php echo $this->formText($form->get('import_date')); ?></td>
    </tr>  
        <tr class="showcase">                 
            <td class="title"><?php echo $this->formLabel($form->get('from_name')); ?></td>
            <td><?php echo $this->formText($form->get('from_name')); ?></td>
        </tr> 
        <tr class="showcase">                 
            <td class="title"><?php echo $this->formLabel($form->get('from_email')); ?></td>
            <td><?php echo $this->formText($form->get('from_email')); ?></td>
        </tr> 
        <tr class="showcase">                 
            <td class="title"><?php echo $this->formLabel($form->get('subject')); ?></td>
            <td><?php echo $this->formText($form->get('subject')); ?></td>
        </tr> 
        <tr class="showcase">                 
            <td class="title"><?php echo $this->formLabel($form->get('body')); ?></td>
            <td><?php echo $this->formTextarea($form->get('body')); ?></td>
        </tr>        


    <tr>
        <td>&nbsp;</td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')); ?>&nbsp;&nbsp;
            <a href="<?php echo $this->url('emailapp');?>" class="btn btn-large btn-primary">Cancel</a>
        </td>
    </tr>
</table>
<?php echo $this->form()->closeTag(); ?> 
<script type="text/javascript">    
    make_wyzz('textarea-editor');
</script>
