<?php
$title = 'View Email List';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<table class="table">
 <tr>
    <th>Name</th>
    <td>:</td>
    <td><?php echo $this->escapeHtml(ucwords($emailapps->name));?></td>
 </tr>
 <tr>
    <th>Email</th>
    <td>:</td>
    <td><?php echo $this->escapeHtml(ucwords($emailapps->email));?></td>
 </tr>
 <tr>
    <th>Content</th>
    <td>:</td>
    <td><?php echo $this->escapeHtml(ucwords($emailapps->content));?></td>
 </tr>
 <tr>
    <th>Imported Date</th>
    <td>:</td>
    <td><?php if($emailapps->import_date != '0000-00-00 00:00:00') 
                        { echo $this->escapeHtml(ucwords($emailapps->import_date)); };?></td>
 </tr>
 <tr>
    <th>Mail Sent</th>
    <td>:</td>
    <td><?php if($emailapps->mail_sent != '0000-00-00 00:00:00') 
                        { echo $this->escapeHtml(ucwords($emailapps->mail_sent)); };?></td>
 </tr>
 <tr>
     <th colspan="3"><a href="<?php echo $this->url('emailapp');?>" class="btn btn-large btn-primary">Back</a></th>
 </tr>
</table>