 <?php
 $title = 'User Management';
 $this->headTitle($title);
 ?>


<script type="text/javascript">    
    $(document).ready(function(){         
        //Search Term Functionality        
        $("#search-term").on('change paste ', function() {
            var search_term = $(this).val();                        
            var url_redirect = location.protocol + '//' + location.host + location.pathname;
            if(search_term!=''){                
                var redirect_url = url_redirect+'?search='+encodeURIComponent(search_term);
                window.location.href = redirect_url;
            } else {
                window.location.href = url_redirect;
            }    
        });        
    });
</script>
<div class="row">
    <div class="col-md-12">
        <h3><?php echo $this->escapeHtml($title); ?></h3>
        <?php
if($this->flashMessenger()->render('error')!='') 
{
    echo '<div class="alert alert-error">'.$this->flashMessenger()->render('error').'</div>';
}
if($this->flashMessenger()->render('success')!='') 
{
    echo '<div class="alert alert-success">'.$this->flashMessenger()->render('success').'</div>';
}
if($this->flashMessenger()->render('info')!='') 
{
    echo '<div class="alert alert-info">'.$this->flashMessenger()->render('info').'</div>';
}
?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Results: ') ?><?php echo $this->escapeHtml($rowCount);?>
                <!-- <span style="float:right;font-size:12px;"><a href="<?php //echo $this->url('users', array('action'=>'add'));?>">Add New</a></span>    -->                    
            </div>
            <?php if($rowCount>0 || $search!='') { ?>
            <div style="text-align:right;display:block;padding:0.8%;font-size:13px;background: #F4F4F4">
                <span style="display:inline-block;">Search:</span> <input type="text" style="display:inline-block;width: 180px !important;" name="search-term" class="form-control" id="search-term" value="<?php if($search!='') echo $search; else echo '';?>"/>
            </div>        
            <?php } ?>
            <table class="table <?php if($rowCount>0): echo 'custom-datatable'; endif;?>">
                <thead>
                 <tr class="panel panel-default">
                        <th class="panel-heading">University</th>
                         <th class="panel-heading">Name</th>
                         <th class="panel-heading">User Name</th>
                         <th class="panel-heading">Email</th>
                         <th class="panel-heading">Role</th>                         
                         <th class="panel-heading">Status</th>
                         <th class="panel-heading align-center" id="data-sorter-false">Action</th>
                 </tr>
                 </thead>
                 <tbody>	
                 <?php if($rowCount>0) { foreach ($users as $user) : ?>
                    <tr class="panel panel-default">
                        <td><?php echo $this->escapeHtml($user->university);?></td>
                        <td><?php echo $this->escapeHtml($user->display_name);?></td>
                        <td><?php echo $this->escapeHtml($user->username);?></td>    
                        <td><?php echo $this->escapeHtml($user->email);?></td>
                        <td><?php echo $this->escapeHtml(ucwords($user->role_name));?></td>                        
                        <td><?php if($user->state) echo 'Active'; else echo 'In-Active'; ?></td>
                        <td id="data-sorter-false">
                            <a href="<?php echo $this->url('users',array('action'=>'view', 'id' => $user->user_id));?>" title="View"><img src="<?php echo $this->basePath().'/img/icon_view.png'?>"></a>&nbsp;
                            <a href="<?php echo $this->url('users',array('action'=>'edit', 'id' => $user->user_id));?>" title="Edit"><img src="<?php echo $this->basePath().'/img/icon_edit.png'?>"></a>&nbsp;
                            <a href="<?php echo $this->url('users',array('action'=>'delete', 'id' => $user->user_id));?>" title="Delete"><img src="<?php echo $this->basePath().'/img/icon_delete.png'?>"></a>
                        </td>
                    </tr>
                 <?php endforeach; } else { ?>
                 <tr class="panel panel-default">
                        <td colspan="7" class="align-center"><?php echo $this->escapeHtml('No internal users registered yet..');?></td>    
                 </tr>
                 <?php } ?>
                 </tbody>
             </table>	
        </div>
    </div> 
 </div>
<?php     
if($rowCount>0) {
    $url = $this->url('users', array('action' => 'index')).'?search='.$search;;
    echo $this->paginationControl($this->users,
        'sliding',
        'partial/paginator.phtml',            
        array(
            'route' =>  $url
        )
    );
}
?>
