<?php
// module/Vendor/view/vendor/vendor/edit.phtml:

$title = 'View User';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<table class="table">

 <tr>
	 <th width="300">User Name</th>
	 <td width="25">:</td>
	 <td><?php echo $this->escapeHtml(ucwords($user->username));?></td>
 </tr>
 
 <tr>
	 <th>Name</th>
	 <td>:</td>
	 <td><?php echo $this->escapeHtml(ucwords($user->display_name));?></td>
 </tr>
 
 <tr>
	 <th>Email</th>
	 <td>:</td>
	 <td><?php echo $this->escapeHtml($user->email);?></td>
 </tr>
  
 <tr>
	 <th>Status</th>
	 <td>:</td>
	 <td><?php if($user->state==1){ echo 'Active'; } else { echo 'Inactive';} ?></td>
 </tr>
 <tr>
     <th colspan="3"><a href="<?php echo $this->url('users');?>" class="btn btn-large btn-primary">Back</a></th>
 </tr>
</table>